### ISSUE TITLE
Add pagination to leaderboards

### ISSUE THREAD

**Issue by evannorton** [evannorton/Retro-MMO.com#5]
Allow providing a query string on the leaderboards (e.g. https://retro-mmo.com/leaderboards?page=2).

Update leaderboards.js so it uses the page value in the request (e.g. https://play.retro-mmo.com/leaderboards.json?page=2).

Use JS to apply the gold/silver/bronze colors for 1st/2nd/3rd place, as the css solution will not work with pagination.

Add pagination buttons to the leaderboards page.

**Comment by amthomps11** [comment]
Hey - I'd be open to working on this!
