### ISSUE TITLE
Show pagination UI both above and below leaderboards table

### ISSUE THREAD

**Issue by evannorton** [evannorton/Retro-MMO.com#8]
Currently it only shows below. It would be nice to have it at the top too.

![image](https://github.com/user-attachments/assets/77833421-90f3-44a2-9991-ca3243f2165e)

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi Evan,

I would like to work on this issue. Could you please assign it to me?

Thank you!

Best regards,
Harsh Tiwari
